export const projects_data = [
  {
    id: 0,
    title: "Weather App",
    img: "./weatherApp.png",
    source_code: "https://github.com/ArtBabarykin/weatherApp",
    url: "https://artbabarykin.github.io/weatherApp/",
  },
  {
    id: 1,
    title: "Number Guesser",
    img: "./numberGuesser.png",
    source_code: "https://github.com/ArtBabarykin/numberGuesser",
    url: "https://artbabarykin.github.io/NumberGuesser/",
  },
  {
    id: 2,
    title: "Messenger",
    img: "./messenger.png",
    source_code: "https://github.com/ArtBabarykin/messenger-app",
    url: "https://facebook-messenger-clone-1a4ed.web.app/",
  },
  {
    id: 3,
    title: "LinkedIn Feed Example",
    img: "./linkedIn.jpeg",
    source_code: "https://github.com/ArtBabarykin/linkedIn-feed",
    url: "https://linkedin-clone-eec88.web.app/",
  },
  {
    id: 4,
    title: "Edge Ledger",
    img: "./edgeLedger.png",
    source_code: "https://github.com/ArtBabarykin/EdgeLedger",
    url: "https://artbabarykin.github.io/EdgeLedger/",
  },

  {
    id: 5,
    title: "Gmail Inbox Example",
    img: "./gmail.jpeg",
    source_code: "https://github.com/ArtBabarykin/gmail-clone",
    url: "https://clone-76ba6.web.app/",
  },
  {
    id: 6,
    title: "Search GitHub User",
    img: "./searchApp.png",
    source_code: "https://github.com/ArtBabarykin/searchGithubUser",
    url: "https://artbabarykin.github.io/searchGithubUser/",
  },
  {
    id: 7,
    title: "Book List",
    img: "./bookList.png",
    source_code: "https://github.com/ArtBabarykin/BookList",
    url: "https://artbabarykin.github.io/BookList/",
  },
  {
    id: 8,
    title: "Slack Feed Example",
    img: "./slack.jpeg",
    source_code: "https://github.com/ArtBabarykin/slack-clone",
    url: "https://slack-clone-2fcda.web.app/",
  },
  {
    id: 9,
    title: "Task List",
    img: "./taskList.png",
    source_code: "https://github.com/ArtBabarykin/taskList",
    url: "https://artbabarykin.github.io/taskList/",
  },
  {
    id: 10,
    title: "Amazon Clone",
    img: "./amazon.jpeg",
    source_code: "https://github.com/ArtBabarykin/amazon-clone",
    url: "https://clone-1d35a.firebaseapp.com/",
  },
  {
    id: 11,
    title: "Loan Calculator",
    img: "./loanCalculator.png",
    source_code: "https://github.com/ArtBabarykin/loanCalculator",
    url: "https://artbabarykin.github.io/loanCalculator/",
  },
];
